apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6i7z
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-6i7z@sha256:657927f247055a764f3f0f77f0eed03e8748cc5e66dfd949309c1dbfc8589d51
        name: my-nodejs
        resources: {}
status: {}
